In [1]:
# Install DuckDB
!pip install duckdb

import duckdb
import pandas as pd

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)

In [6]:
from google.colab import files

uploaded = files.upload()

Saving archive (6).zip to archive (6).zip

In [9]:
import pandas as pd
import zipfile
import os

# Unzip the archive
zip_file_name = 'archive (6).zip'
with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall('.')

# Assuming the CSVs are in a subfolder after unzipping, e.g., 'banking_dataset_kaggle/data/csv/'
# You might need to adjust this path based on the actual structure inside the zip file.
# Let's check the common path based on the previous context provided in kernel state.
# From the 'uploaded' variable: 'banking_dataset_kaggle/data/csv/accounts.csv'

data_path = 'banking_dataset_kaggle/data/csv/'

customers = pd.read_csv(os.path.join(data_path, "customers.csv"))
accounts = pd.read_csv(os.path.join(data_path, "accounts.csv"))
loans = pd.read_csv(os.path.join(data_path, "loans.csv"))
cards = pd.read_csv(os.path.join(data_path, "cards.csv"))
branches = pd.read_csv(os.path.join(data_path, "branches.csv"))
merchants = pd.read_csv(os.path.join(data_path, "merchants.csv"))

In [10]:
con = duckdb.connect()

con.register("customers", customers)
con.register("accounts", accounts)
con.register("loans", loans)
con.register("cards", cards)
con.register("branches", branches)
con.register("merchants", merchants)

In [11]:
query = """
SELECT COUNT(*) AS Total_Customers
FROM customers;
"""

con.execute(query).df()

   Total_Customers
0            50000

In [12]:
query = """
SELECT COUNT(*) AS Total_Accounts
FROM accounts;
"""

con.execute(query).df()

   Total_Accounts
0           75000

In [14]:
query = """
SELECT COUNT(*) AS Total_Loans
FROM loans;
"""

con.execute(query).df()

   Total_Loans
0        30000

In [15]:
query = """
SELECT COUNT(*) AS Total_Cards
FROM cards;
"""

con.execute(query).df()

   Total_Cards
0       100000

In [16]:
query = """
SELECT AVG(balance_usd) AS Average_Balance
FROM accounts;
"""

con.execute(query).df()

   Average_Balance
0    100181.721881

In [17]:
query = """
SELECT SUM(balance_usd) AS Total_Deposit
FROM accounts;
"""

con.execute(query).df()

   Total_Deposit
0   7.513629e+09

In [18]:
query = """
SELECT MAX(balance_usd) AS Maximum_Deposit
FROM accounts;
"""

con.execute(query).df()

   Maximum_Deposit
0        199994.58

In [19]:
query = """
SELECT MIN(balance_usd) AS Minimum_Deposit
FROM accounts;
"""

con.execute(query).df()

   Minimum_Deposit
0             13.2

In [20]:
query = """
SELECT AVG(loan_amount) AS Average_Loan
FROM loans;
"""

con.execute(query).df()

    Average_Loan
0  150089.016603

In [21]:
query = """
SELECT SUM(loan_amount) AS Total_Loan
FROM loans;
"""

con.execute(query).df()

     Total_Loan
0  4.502670e+09

In [22]:
query = """
SELECT city,
COUNT(*) AS Customers
FROM customers
GROUP BY city
ORDER BY Customers DESC;
"""

con.execute(query).df()

                    city  Customers
0          South Michael         51
1            New Michael         50
2             Smithmouth         50
3           West Michael         46
4           East Michael         44
...                  ...        ...
25164  North Danielshire          1
25165    North Jacobbury          1
25166     Lake Tylerview          1
25167   West Bradleyside          1
25168  West Herberthaven          1

[25169 rows x 2 columns]

In [23]:
query = """
SELECT account_type,
COUNT(*) AS Accounts
FROM accounts
GROUP BY account_type;
"""

con.execute(query).df()

  account_type  Accounts
0     Checking     25090
1     Business     24948
2      Savings     24962

In [24]:
query = """
SELECT account_type,
SUM(balance_usd) AS Deposit
FROM accounts
GROUP BY account_type;
"""

con.execute(query).df()

  account_type       Deposit
0     Checking  2.512713e+09
1     Business  2.498665e+09
2      Savings  2.502251e+09

In [25]:
query = """
SELECT account_type,
AVG(balance_usd) AS Avg_Balance
FROM accounts
GROUP BY account_type;
"""

con.execute(query).df()

  account_type    Avg_Balance
0     Checking  100147.970631
1     Business  100154.938045
2      Savings  100242.415014

In [26]:
query = """
SELECT *
FROM customers
WHERE credit_score > 700;
"""

con.execute(query).df()

,customer_id,first_name,last_name,email,city,credit_score,created_at
0,CUSCBLSKRT05UIR,Vanessa,Gonzalez,mortonrichard@example.com,Markside,716,2021-02-18
1,CUSFRHOCN9J2QP8,Teresa,Craig,rayjonathan@example.org,Richardstad,798,2020-09-26
2,CUS5OWF75935A0L,Tyler,Cherry,charlesstephenson@example.net,Lake Allisonshire,721,2021-10-13
3,CUSXN0GUO4KH2VL,Patrick,Villanueva,sarahperez@example.com,Port Tammieshire,752,2023-12-17
4,CUS6452H2ZQU7EE,Robert,Brown,wgoodman@example.org,Lake Victoria,775,2024-12-15
...,...,...,...,...,...,...,...
13499,CUSXSE8SBXMP066,Lisa,Fox,bakerwilliam@example.com,Lake Andrewchester,784,2025-01-22
13500,CUSMMH8BYFZ3261,William,Robinson,claudia59@example.org,Sydneystad,831,2022-02-12
13501,CUS287HK3W659NS,Kelly,Moore,emily72@example.net,Edwardfort,773,2022-05-14
13502,CUS3393NRRUTTA9,Timothy,Rogers,monroesandra@example.org,Lambertfort,756,2024-07-05
13503,CUSDT2QC0P1XO65,Monique,Williams,jsanchez@example.com,Michaelhaven,751,2020-09-24

In [27]:
query = """
SELECT customer_id,
SUM(balance_usd) AS Total_Balance
FROM accounts
GROUP BY customer_id
ORDER BY Total_Balance DESC
LIMIT 10;
"""

con.execute(query).df()

       customer_id  Total_Balance
0  CUSEPV1YW0Y2JL9     1020344.41
1  CUSN2LWQV1UR1PY      998074.92
2  CUS3JY2UIFZ7123      935146.22
3  CUSM3X4B2DTTNOO      932783.59
4  CUSHMODKKCZTNRF      928661.73
5  CUSVFI1KMDWBWNP      888434.52
6  CUSIJ61KQCG1IV8      885857.36
7  CUSXVL4YRQRDZHJ      859286.03
8  CUSHMDV47IQRPIC      851916.54
9  CUSDCD4K37ULEHP      840288.34

In [28]:
query = """
SELECT city,
AVG(credit_score) AS Average_Credit
FROM customers
GROUP BY city;
"""

con.execute(query).df()

                    city  Average_Credit
0           Martinezside           560.6
1           Gallowayfurt           670.0
2             Morrisview           573.0
3              Lake Anna           530.4
4         New Javierbury           694.0
...                  ...             ...
25164  North Danielshire           446.0
25165    North Jacobbury           515.0
25166     Lake Tylerview           687.0
25167   West Bradleyside           419.0
25168  West Herberthaven           816.0

[25169 rows x 2 columns]

In [30]:
query = """
SELECT YEAR(CAST(open_date AS DATE)) AS Year,
COUNT(*) AS Accounts
FROM accounts
GROUP BY Year;
"""

con.execute(query).df()

   Year  Accounts
0  2021     10800
1  2019     10510
2  2023     10733
3  2024     10759
4  2022     10564
5  2025     10911
6  2020     10723

In [32]:
query = """
SELECT YEAR(CAST(start_date AS DATE)) AS Year,
COUNT(*) AS Loans
FROM loans
GROUP BY Year;
"""

con.execute(query).df()

   Year  Loans
0  2024   4266
1  2022   4307
2  2019   4393
3  2025   4319
4  2021   4297
5  2023   4211
6  2020   4207

In [33]:
query = """
SELECT AVG(interest_rate) AS Average_Interest
FROM loans;
"""

con.execute(query).df()

   Average_Interest
0          8.507418

In [34]:
query = """
SELECT
SUM(l.loan_amount) / SUM(a.balance_usd) AS Loan_Deposit_Ratio
FROM loans l
JOIN accounts a
ON l.customer_id = a.customer_id;
"""

con.execute(query).df()

   Loan_Deposit_Ratio
0            1.505461

In [35]:
query = """
SELECT
customer_id,
SUM(balance_usd) AS Deposit,
RANK() OVER(ORDER BY SUM(balance_usd) DESC) AS Ranking
FROM accounts
GROUP BY customer_id;
"""

con.execute(query).df()

           customer_id     Deposit  Ranking
0      CUSEPV1YW0Y2JL9  1020344.41        1
1      CUSN2LWQV1UR1PY   998074.92        2
2      CUS3JY2UIFZ7123   935146.22        3
3      CUSM3X4B2DTTNOO   932783.59        4
4      CUSHMODKKCZTNRF   928661.73        5
...                ...         ...      ...
38833  CUS7OH7R0CJU0EC       68.05    38834
38834  CUSLG1SPDQZOIYH       54.78    38835
38835  CUSR0P5UNM3ZAQS       46.17    38836
38836  CUSXZ5IST4T86UZ       27.59    38837
38837  CUS27D326TP8SFA       13.20    38838

[38838 rows x 3 columns]

In [36]:
query = """
SELECT
customer_id,
SUM(balance_usd) AS Deposit,
DENSE_RANK() OVER(ORDER BY SUM(balance_usd) DESC) AS Dense_Rank
FROM accounts
GROUP BY customer_id;
"""

con.execute(query).df()

           customer_id     Deposit  Dense_Rank
0      CUSEPV1YW0Y2JL9  1020344.41           1
1      CUSN2LWQV1UR1PY   998074.92           2
2      CUS3JY2UIFZ7123   935146.22           3
3      CUSM3X4B2DTTNOO   932783.59           4
4      CUSHMODKKCZTNRF   928661.73           5
...                ...         ...         ...
38833  CUS7OH7R0CJU0EC       68.05       38819
38834  CUSLG1SPDQZOIYH       54.78       38820
38835  CUSR0P5UNM3ZAQS       46.17       38821
38836  CUSXZ5IST4T86UZ       27.59       38822
38837  CUS27D326TP8SFA       13.20       38823

[38838 rows x 3 columns]

In [37]:
query = """
SELECT
open_date,
SUM(balance_usd) OVER(ORDER BY open_date) AS Running_Total
FROM accounts;
"""

con.execute(query).df()

        open_date  Running_Total
0      2019-01-01   2.517961e+06
1      2019-01-01   2.517961e+06
2      2019-01-01   2.517961e+06
3      2019-01-01   2.517961e+06
4      2019-01-01   2.517961e+06
...           ...            ...
74995  2025-12-31   7.513629e+09
74996  2025-12-31   7.513629e+09
74997  2025-12-31   7.513629e+09
74998  2025-12-31   7.513629e+09
74999  2025-12-31   7.513629e+09

[75000 rows x 2 columns]

In [38]:
query = """
SELECT *
FROM accounts
WHERE balance_usd >
(
SELECT AVG(balance_usd)
FROM accounts
);
"""

con.execute(query).df()

            account_id      customer_id account_type  balance_usd   open_date
0      ACCOD48PUCAEHKH  CUSAEOACKBH8CK6     Checking    182700.46  2021-03-27
1      ACCZT96PKCU0WD9  CUSDMISW804XPRO     Business    180076.81  2021-12-19
2      ACCXTK5RZJLV6C4  CUSSI6L5SODYNTG      Savings    113502.83  2022-01-01
3      ACC44HPKAAOS2L0  CUSA9P9URVI8PJ6     Checking    164330.33  2025-09-29
4      ACCOWHP5V1N5VQM  CUSXPAWQPOE9FWC      Savings    198043.33  2021-06-24
...                ...              ...          ...          ...         ...
37543  ACCSO66W9WGH51A  CUSJPQGVP2YL7Z5      Savings    119725.73  2025-04-15
37544  ACCACCISARV84VQ  CUSOTE0Q32RV23U      Savings    150119.17  2019-05-10
37545  ACCLF5KFA0OYML3  CUSXXS8J3RO3177     Checking    199538.19  2025-01-13
37546  ACCJ2LPOTD36ZL6  CUSDC20YYZK2XBF     Checking    192680.69  2025-05-10
37547  ACC0VS654VM7Z1C  CUS4WVVOPXXEGSB     Checking    119505.81  2023-02-13

[37548 rows x 5 columns]

In [39]:
query = """
WITH Deposit AS
(
SELECT
customer_id,
SUM(balance_usd) AS Total_Deposit
FROM accounts
GROUP BY customer_id
)

SELECT *
FROM Deposit
WHERE Total_Deposit > 100000;
"""

con.execute(query).df()

           customer_id  Total_Deposit
0      CUSAEOACKBH8CK6      389215.84
1      CUSNUWQT2EXWNSC      259740.50
2      CUSDMISW804XPRO      806282.32
3      CUSSI6L5SODYNTG      548917.89
4      CUSBQNS6ND3E3D8      411964.28
...                ...            ...
28825  CUSTDESY3U0SL3E      141105.21
28826  CUSTN75FSRMW2Q7      125666.08
28827  CUSHZBT69161GTD      154144.89
28828  CUS8V82IR3C5XZX      148488.33
28829  CUS4WVVOPXXEGSB      119505.81

[28830 rows x 2 columns]

In [40]:
query = """
SELECT
c.customer_id,
c.city,
a.account_type,
a.balance_usd
FROM customers c
JOIN accounts a
ON c.customer_id = a.customer_id;
"""

con.execute(query).df()

           customer_id           city account_type  balance_usd
0      CUSAEOACKBH8CK6      New David     Checking    182700.46
1      CUSKI0ABUBGCLFD    Vanessaview      Savings     57886.71
2      CUSWXG0ESCUG77M     Alyssafort     Business     68774.44
3      CUSUTT52LK3TW0J  Lake Johntown     Business     67015.68
4      CUSNUWQT2EXWNSC     West Kelly      Savings     67265.67
...                ...            ...          ...          ...
74995  CUSML6DVZNVOTES    North Erica      Savings     64095.88
74996  CUSIHEDKAB0C7FW       Alanstad     Business     13904.42
74997  CUSFEW5CWHU9HZK     Lake David      Savings     19009.31
74998  CUSO0NX8NPL40L2   West Marissa      Savings     87440.52
74999  CUST84K7Y8VI7GY   West Matthew      Savings     63892.97

[75000 rows x 4 columns]

In [41]:
query = """
SELECT
c.customer_id,
c.credit_score,
l.loan_amount
FROM customers c
JOIN loans l
ON c.customer_id = l.customer_id;
"""

con.execute(query).df()

           customer_id  credit_score  loan_amount
0      CUSXAJI0Y6DPBHS           327    178482.76
1      CUSDD4V30T9NT3W           670      2441.32
2      CUSOC6UZHR5XFF0           569     42652.71
3      CUSVQJT7YE511MK           461     79328.67
4      CUSAZZ81SDW4SHN           465     55308.95
...                ...           ...          ...
29995  CUSMTE4TSZ1PWZ4           383    143937.93
29996  CUSQIKDII54GI3U           611    132538.98
29997  CUSLAWT021P787R           405      6643.61
29998  CUS97BXXF7IDOM5           383    178837.86
29999  CUSX3JDL6REZTTL           508    121847.23

[30000 rows x 3 columns]

In [43]:
query = """
SELECT
c.customer_id,
ca.card_type
FROM customers c
JOIN accounts a
ON c.customer_id = a.customer_id
JOIN cards ca
ON a.account_id = ca.account_id;
"""

con.execute(query).df()

           customer_id card_type
0      CUS1PVOPNQ5NOIN     Debit
1      CUSFLE69M3I1RAJ    Credit
2      CUSY56VWIOYTCHK    Credit
3      CUSLIU05PJZJRFC     Debit
4      CUSQ6SVR0IIWV25    Credit
...                ...       ...
99995  CUSMG3F2MDQIR0H     Debit
99996  CUSDC7PMQKA5CB9    Credit
99997  CUSQQRE30H2DMN6     Debit
99998  CUSF07UCG9JT76B     Debit
99999  CUSZXGKFGHCAK5U     Debit

[100000 rows x 2 columns]

In [44]:
query = """
SELECT
COUNT(DISTINCT customer_id) AS Customers,
SUM(balance_usd) AS Total_Deposit,
AVG(balance_usd) AS Average_Deposit
FROM accounts;
"""

con.execute(query).df()

   Customers  Total_Deposit  Average_Deposit
0      38838   7.513629e+09    100181.721881

In [45]:
query = """
SELECT *
FROM customers
WHERE credit_score >
(
SELECT AVG(credit_score)
FROM customers
);
"""

con.execute(query).df()

,customer_id,first_name,last_name,email,city,credit_score,created_at
0,CUSHXTHV3A3ZMF8,Jason,Clements,toddwilliam@example.net,Martinezside,644,2020-02-23
1,CUSDD4V30T9NT3W,Randy,Thompson,trevoranderson@example.org,Gallowayfurt,670,2025-06-22
2,CUSPVN9ER14FFYV,Morgan,Miller,narnold@example.org,New Javierbury,694,2023-04-13
3,CUSCBLSKRT05UIR,Vanessa,Gonzalez,mortonrichard@example.com,Markside,716,2021-02-18
4,CUSFRHOCN9J2QP8,Teresa,Craig,rayjonathan@example.org,Richardstad,798,2020-09-26
...,...,...,...,...,...,...,...
25048,CUS287HK3W659NS,Kelly,Moore,emily72@example.net,Edwardfort,773,2022-05-14
25049,CUS3393NRRUTTA9,Timothy,Rogers,monroesandra@example.org,Lambertfort,756,2024-07-05
25050,CUSO3FGVU4ZSI03,Kristina,Chavez,rchen@example.net,Lake Christopherbury,593,2022-06-30
25051,CUSDT2QC0P1XO65,Monique,Williams,jsanchez@example.com,Michaelhaven,751,2020-09-24
25052,CUS9U01H8I3F6EA,Julia,Bowen,valdezdanielle@example.com,North Robert,606,2024-07-25

In [46]:
query = """
SELECT *
FROM customers
WHERE credit_score <
(
SELECT AVG(credit_score)
FROM customers
);
"""

con.execute(query).df()

,customer_id,first_name,last_name,email,city,credit_score,created_at
0,CUSXAJI0Y6DPBHS,Kevin,Young,brauncameron@example.net,North Williamville,327,2025-04-17
1,CUSGCX1945NQ4FM,Laura,Phillips,valdezgeorge@example.com,Morrisview,573,2019-10-20
2,CUSVG0FN9XUY41I,Savannah,Swanson,smithluis@example.com,Lake Anna,332,2022-07-16
3,CUSOC6UZHR5XFF0,Ashley,Wang,reesekendra@example.com,Amybury,569,2025-07-22
4,CUSVQJT7YE511MK,David,Cabrera,heidi41@example.net,West Michelle,461,2024-02-02
...,...,...,...,...,...,...,...
24942,CUS7853IMWY2FPH,Michelle,Atkinson,twalsh@example.net,North Craig,388,2022-10-06
24943,CUSB1O2FN65T8JN,Daniel,Willis,plee@example.net,West David,362,2019-08-13
24944,CUSK0CL1UZVQZEZ,Frederick,Payne,michellemahoney@example.com,North Jeremyfurt,540,2022-11-25
24945,CUSV942FEOLVOZD,Stephen,Young,qcastillo@example.net,Michaelfurt,464,2023-07-14
24946,CUS620UGPBHHIV2,Marcus,Warner,stevensonjames@example.net,Bowmanton,499,2023-11-03

In [47]:
query = """
SELECT *
FROM accounts
WHERE balance_usd >
(
SELECT AVG(balance_usd)
FROM accounts
);
"""

con.execute(query).df()

            account_id      customer_id account_type  balance_usd   open_date
0      ACCOD48PUCAEHKH  CUSAEOACKBH8CK6     Checking    182700.46  2021-03-27
1      ACCZT96PKCU0WD9  CUSDMISW804XPRO     Business    180076.81  2021-12-19
2      ACCXTK5RZJLV6C4  CUSSI6L5SODYNTG      Savings    113502.83  2022-01-01
3      ACC44HPKAAOS2L0  CUSA9P9URVI8PJ6     Checking    164330.33  2025-09-29
4      ACCOWHP5V1N5VQM  CUSXPAWQPOE9FWC      Savings    198043.33  2021-06-24
...                ...              ...          ...          ...         ...
37543  ACCSO66W9WGH51A  CUSJPQGVP2YL7Z5      Savings    119725.73  2025-04-15
37544  ACCACCISARV84VQ  CUSOTE0Q32RV23U      Savings    150119.17  2019-05-10
37545  ACCLF5KFA0OYML3  CUSXXS8J3RO3177     Checking    199538.19  2025-01-13
37546  ACCJ2LPOTD36ZL6  CUSDC20YYZK2XBF     Checking    192680.69  2025-05-10
37547  ACC0VS654VM7Z1C  CUS4WVVOPXXEGSB     Checking    119505.81  2023-02-13

[37548 rows x 5 columns]

In [48]:
query = """
SELECT *
FROM accounts
ORDER BY balance_usd DESC
LIMIT 20;
"""

con.execute(query).df()

         account_id      customer_id account_type  balance_usd   open_date
0   ACCYWA9TSM1GXTG  CUSEXB4Z7J8HWE2     Checking    199994.58  2022-08-26
1   ACC5HOPZOH2VAZX  CUS05F95VDL5G26      Savings    199989.26  2021-09-07
2   ACCSRWHMGDL92R2  CUSTCFNYEBCRW2Y     Business    199969.50  2019-09-28
3   ACCKNEQVI7LDS4Y  CUSFSEINJWX8QJ5     Business    199968.62  2022-11-05
4   ACC92CJD3LIRR0X  CUSXKDR73U5XXC8     Business    199965.37  2024-08-15
5   ACCNUR2OMRJAFA2  CUSI7GKRTQLXK5F      Savings    199963.49  2020-06-23
6   ACC3HQFDY5BQ3TV  CUSXKXUPNM6VUWR      Savings    199963.38  2022-11-02
7   ACC31UVSUZFS8QX  CUSVMJB7L3FQ5AX     Checking    199961.03  2024-12-08
8   ACCD0TU30OTVMXU  CUSLGUPUOWOB7P7     Business    199958.24  2019-07-19
9   ACCODRZK7G0T999  CUSSKZH0SZOHX2H      Savings    199956.88  2023-06-25
10  ACCI1J92D6TPZXO  CUSBELKO48DHCBZ      Savings    199956.15  2025-09-24
11  ACCOBI9GVEVS85J  CUSIUHJBS6K6081     Checking    199956.06  2019-02-08
12  ACCU6FXSLOAC9NI  CUSELI917D1ZKUE      Savings    199955.81  2023-06-21
13  ACCLQ1DKGSILCNI  CUS1CO6KC9DRXDL     Business    199955.81  2020-09-08
14  ACCH6QY2DEWRJGP  CUSLDKUW1H8SO8H     Checking    199954.00  2025-09-05
15  ACCHFYGU200DV47  CUSMREBD1IXK51X     Business    199953.94  2020-03-17
16  ACCAE66UIGN0XR0  CUSHSGR27FFTG4C     Business    199953.22  2019-12-04
17  ACC3TP0MCOE8C19  CUSHZ8EEKC8U091      Savings    199953.18  2020-09-01
18  ACCSDT54E22HMUR  CUSDK45DXGUZB89      Savings    199952.44  2021-07-10
19  ACCA6UH4SIO9ZUJ  CUS0XPDKZPNABKG     Checking    199947.88  2025-11-05

In [49]:
query = """
SELECT *
FROM loans
ORDER BY loan_amount DESC
LIMIT 20;
"""

con.execute(query).df()

            loan_id      customer_id  loan_amount  interest_rate  start_date
0   LON2VLMPRF92KMA  CUS9R8QO64GS540    299975.47           7.34  2020-09-19
1   LONQ5T1ILE2ZE68  CUSPYS71SMSGB52    299967.79          13.79  2023-07-02
2   LON1SUTLWP8HZAN  CUSSV1SPPFFGX3Y    299959.70          14.82  2024-09-28
3   LONHOSF67J67DTY  CUSDMS8KRN7JG60    299951.14          10.74  2025-07-05
4   LONSUVYX8CC400V  CUSSF97K7GTGZ33    299933.30           2.89  2022-09-19
5   LONTHXHQ0DOG63L  CUSU1RI2WN10A53    299932.58          14.94  2025-10-30
6   LONCE44DRXS2150  CUSL0T8XQ1WACI9    299928.98          14.46  2020-11-13
7   LONRM71OLQMHZUE  CUS0PLOJMJFYY97    299907.74          14.36  2022-07-07
8   LONI6ZFEANF08S8  CUSQNN47Y3Q4I5B    299889.84           3.46  2023-06-07
9   LONL5ZOE4UTGM9R  CUS0CVHEJRL7MLT    299887.82           2.32  2024-07-01
10  LONUE6CCGNT760V  CUSTQ9DAGETLZT4    299885.04           7.03  2022-11-04
11  LONB0R29VGO9VND  CUS3Q23DDQOBOEY    299878.76          11.73  2019-09-28
12  LON3JZW2GE6R4DT  CUSE9QLJMFDXQWJ    299871.25          13.66  2025-09-25
13  LONTRSQKW7RUS56  CUSPEQBCWJH2LHG    299865.94          13.13  2019-04-16
14  LONPA9TX3A5P059  CUSAU91AGAGIY4V    299851.87           6.50  2025-08-02
15  LONM844JAHB3T0R  CUSU5M767JEZ24W    299850.55          11.76  2022-08-05
16  LONL8VIPSDU4MVJ  CUSJ3OKEKSK2VPA    299847.76          14.49  2019-02-14
17  LONW4VEE4C8F81X  CUSK7GQD93NUEB1    299846.32          11.71  2022-03-27
18  LONF2SB3TB2EAPT  CUSH72E828WNSYL    299803.09           5.80  2020-07-23
19  LONQQ0XGI48SOL1  CUS7PDHLOOC62YG    299800.92           2.74  2022-06-28

In [50]:
query = """
SELECT
customer_id,
SUM(balance_usd) AS Deposit,
RANK() OVER(ORDER BY SUM(balance_usd) DESC) AS Ranking
FROM accounts
GROUP BY customer_id;
"""

con.execute(query).df()

           customer_id     Deposit  Ranking
0      CUSEPV1YW0Y2JL9  1020344.41        1
1      CUSN2LWQV1UR1PY   998074.92        2
2      CUS3JY2UIFZ7123   935146.22        3
3      CUSM3X4B2DTTNOO   932783.59        4
4      CUSHMODKKCZTNRF   928661.73        5
...                ...         ...      ...
38833  CUS7OH7R0CJU0EC       68.05    38834
38834  CUSLG1SPDQZOIYH       54.78    38835
38835  CUSR0P5UNM3ZAQS       46.17    38836
38836  CUSXZ5IST4T86UZ       27.59    38837
38837  CUS27D326TP8SFA       13.20    38838

[38838 rows x 3 columns]

In [51]:
query = """
SELECT
customer_id,
SUM(balance_usd) AS Deposit,
DENSE_RANK() OVER(ORDER BY SUM(balance_usd) DESC) AS Dense_Rank
FROM accounts
GROUP BY customer_id;
"""

con.execute(query).df()

           customer_id     Deposit  Dense_Rank
0      CUSEPV1YW0Y2JL9  1020344.41           1
1      CUSN2LWQV1UR1PY   998074.92           2
2      CUS3JY2UIFZ7123   935146.22           3
3      CUSM3X4B2DTTNOO   932783.59           4
4      CUSHMODKKCZTNRF   928661.73           5
...                ...         ...         ...
38833  CUS7OH7R0CJU0EC       68.05       38819
38834  CUSLG1SPDQZOIYH       54.78       38820
38835  CUSR0P5UNM3ZAQS       46.17       38821
38836  CUSXZ5IST4T86UZ       27.59       38822
38837  CUS27D326TP8SFA       13.20       38823

[38838 rows x 3 columns]

In [52]:
query = """
SELECT
customer_id,
SUM(balance_usd) AS Deposit,
ROW_NUMBER() OVER(ORDER BY SUM(balance_usd) DESC) AS Row_Num
FROM accounts
GROUP BY customer_id;
"""

con.execute(query).df()

           customer_id     Deposit  Row_Num
0      CUSEPV1YW0Y2JL9  1020344.41        1
1      CUSN2LWQV1UR1PY   998074.92        2
2      CUS3JY2UIFZ7123   935146.22        3
3      CUSM3X4B2DTTNOO   932783.59        4
4      CUSHMODKKCZTNRF   928661.73        5
...                ...         ...      ...
38833  CUS7OH7R0CJU0EC       68.05    38834
38834  CUSLG1SPDQZOIYH       54.78    38835
38835  CUSR0P5UNM3ZAQS       46.17    38836
38836  CUSXZ5IST4T86UZ       27.59    38837
38837  CUS27D326TP8SFA       13.20    38838

[38838 rows x 3 columns]

In [53]:
query = """
SELECT
open_date,
balance_usd,
SUM(balance_usd)
OVER(ORDER BY open_date)
AS Running_Total
FROM accounts;
"""

con.execute(query).df()

        open_date  balance_usd  Running_Total
0      2019-01-01    113795.17   2.517961e+06
1      2019-01-01     46020.22   2.517961e+06
2      2019-01-01     95269.12   2.517961e+06
3      2019-01-01    128742.77   2.517961e+06
4      2019-01-01    189448.87   2.517961e+06
...           ...          ...            ...
74995  2025-12-31     75532.32   7.513629e+09
74996  2025-12-31    162721.01   7.513629e+09
74997  2025-12-31    156765.15   7.513629e+09
74998  2025-12-31     39381.93   7.513629e+09
74999  2025-12-31    187374.04   7.513629e+09

[75000 rows x 3 columns]

In [54]:
query = """
SELECT
open_date,
balance_usd,
AVG(balance_usd)
OVER(
ORDER BY open_date
ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
) AS Moving_Average
FROM accounts;
"""

con.execute(query).df()

        open_date  balance_usd  Moving_Average
0      2019-01-01    113795.17   113795.170000
1      2019-01-01     46020.22    79907.695000
2      2019-01-01     95269.12    85028.170000
3      2019-01-01    128742.77    90010.703333
4      2019-01-01    189448.87   137820.253333
...           ...          ...             ...
74995  2025-12-31     75532.32    96521.406667
74996  2025-12-31    162721.01   108914.926667
74997  2025-12-31    156765.15   131672.826667
74998  2025-12-31     39381.93   119622.696667
74999  2025-12-31    187374.04   127840.373333

[75000 rows x 3 columns]

In [55]:
query = """
SELECT
CASE
WHEN credit_score <500 THEN 'Poor'
WHEN credit_score BETWEEN 500 AND 650 THEN 'Fair'
WHEN credit_score BETWEEN 651 AND 750 THEN 'Good'
ELSE 'Excellent'
END AS Credit_Category,
COUNT(*) AS Customers
FROM customers
GROUP BY Credit_Category;
"""

con.execute(query).df()

  Credit_Category  Customers
0            Poor      18158
1            Fair      13820
2            Good       9063
3       Excellent       8959

In [56]:
query = """
SELECT
CASE
WHEN balance_usd <1000 THEN 'Low'
WHEN balance_usd BETWEEN 1000 AND 5000 THEN 'Medium'
ELSE 'High'
END AS Deposit_Category,
COUNT(*) AS Accounts
FROM accounts
GROUP BY Deposit_Category;
"""

con.execute(query).df()

  Deposit_Category  Accounts
0           Medium      1490
1             High     73126
2              Low       384

In [57]:
query = """
SELECT
c.city,
AVG(a.balance_usd) AS Avg_Deposit
FROM customers c
JOIN accounts a
ON c.customer_id=a.customer_id
GROUP BY c.city
ORDER BY Avg_Deposit DESC;
"""

con.execute(query).df()

                     city  Avg_Deposit
0             Port Carmen    199968.62
1          Port Dillonton    199965.37
2              Willieview    199958.24
3      South Aaronborough    199928.46
4       South Samuelshire    199917.06
...                   ...          ...
21214      South Davidton       164.49
21215         Lake Marvin       160.64
21216    Port Lorichester       128.35
21217       Alejandrobury        68.05
21218           East Evan        13.20

[21219 rows x 2 columns]

In [58]:
query = """
SELECT
c.city,
SUM(l.loan_amount) AS Total_Loan
FROM customers c
JOIN loans l
ON c.customer_id=l.customer_id
GROUP BY c.city
ORDER BY Total_Loan DESC;
"""

con.execute(query).df()

                      city  Total_Loan
0               Port David  5389351.88
1              New Michael  5024552.17
2               Smithmouth  4811364.27
3            South Michael  4549725.53
4             West Michael  4524005.50
...                    ...         ...
14442         Madisonburgh     1225.89
14443  Lake Suzanneborough     1173.48
14444           South Seth     1150.62
14445         North Gloria     1120.86
14446            Hodgeview     1054.70

[14447 rows x 2 columns]

In [59]:
query = """
SELECT
c.customer_id,
c.city,
a.account_type,
a.balance_usd
FROM customers c
INNER JOIN accounts a
ON c.customer_id=a.customer_id;
"""

con.execute(query).df()

           customer_id           city account_type  balance_usd
0      CUSAEOACKBH8CK6      New David     Checking    182700.46
1      CUSKI0ABUBGCLFD    Vanessaview      Savings     57886.71
2      CUSWXG0ESCUG77M     Alyssafort     Business     68774.44
3      CUSUTT52LK3TW0J  Lake Johntown     Business     67015.68
4      CUSNUWQT2EXWNSC     West Kelly      Savings     67265.67
...                ...            ...          ...          ...
74995  CUSML6DVZNVOTES    North Erica      Savings     64095.88
74996  CUSIHEDKAB0C7FW       Alanstad     Business     13904.42
74997  CUSFEW5CWHU9HZK     Lake David      Savings     19009.31
74998  CUSO0NX8NPL40L2   West Marissa      Savings     87440.52
74999  CUST84K7Y8VI7GY   West Matthew      Savings     63892.97

[75000 rows x 4 columns]

In [60]:
query = """
SELECT
c.customer_id,
c.credit_score,
l.loan_amount
FROM customers c
INNER JOIN loans l
ON c.customer_id=l.customer_id;
"""

con.execute(query).df()

           customer_id  credit_score  loan_amount
0      CUSXAJI0Y6DPBHS           327    178482.76
1      CUSDD4V30T9NT3W           670      2441.32
2      CUSOC6UZHR5XFF0           569     42652.71
3      CUSVQJT7YE511MK           461     79328.67
4      CUSAZZ81SDW4SHN           465     55308.95
...                ...           ...          ...
29995  CUSMTE4TSZ1PWZ4           383    143937.93
29996  CUSQIKDII54GI3U           611    132538.98
29997  CUSLAWT021P787R           405      6643.61
29998  CUS97BXXF7IDOM5           383    178837.86
29999  CUSX3JDL6REZTTL           508    121847.23

[30000 rows x 3 columns]

In [62]:
query = """
SELECT
c.customer_id,
ca.card_type
FROM customers c
INNER JOIN accounts a
ON c.customer_id = a.customer_id
INNER JOIN cards ca
ON a.account_id = ca.account_id;
"""

con.execute(query).df()

           customer_id card_type
0      CUS1PVOPNQ5NOIN     Debit
1      CUSFLE69M3I1RAJ    Credit
2      CUSY56VWIOYTCHK    Credit
3      CUSLIU05PJZJRFC     Debit
4      CUSQ6SVR0IIWV25    Credit
...                ...       ...
99995  CUSMG3F2MDQIR0H     Debit
99996  CUSDC7PMQKA5CB9    Credit
99997  CUSQQRE30H2DMN6     Debit
99998  CUSF07UCG9JT76B     Debit
99999  CUSZXGKFGHCAK5U     Debit

[100000 rows x 2 columns]

In [63]:
query = """
SELECT DISTINCT customer_id
FROM loans;
"""

con.execute(query).df()

           customer_id
0      CUSK3SW6KH12S96
1      CUS7D2AZQQGCDHI
2      CUSJ7KYVHT6ZWCH
3      CUSXOL4RMHAJ3F0
4      CUSIUFWOFRYTP4D
...                ...
22581  CUS5OIQTW4K9QKU
22582  CUSEV06BB3869TB
22583  CUSDNYLP05JN1P6
22584  CUS4ATY4F7YNOSZ
22585  CUS9J49Q207YU5Q

[22586 rows x 1 columns]

In [65]:
query = """
SELECT DISTINCT a.customer_id
FROM cards ca
JOIN accounts a
ON ca.account_id = a.account_id;
"""

con.execute(query).df()

           customer_id
0      CUSKI0ABUBGCLFD
1      CUSNUWQT2EXWNSC
2      CUSDMISW804XPRO
3      CUSSI6L5SODYNTG
4      CUSXPAWQPOE9FWC
...                ...
33499  CUS0T3OO60QLC8V
33500  CUSM1D2OWJOLAFU
33501  CUSTN75FSRMW2Q7
33502  CUSHZBT69161GTD
33503  CUS4WVVOPXXEGSB

[33504 rows x 1 columns]

In [67]:
query = """
SELECT DISTINCT l.customer_id
FROM loans l
INNER JOIN accounts a
ON l.customer_id = a.customer_id
INNER JOIN cards c
ON a.account_id = c.account_id;
"""

con.execute(query).df()

           customer_id
0      CUS1PVOPNQ5NOIN
1      CUSC8HPR9CJOJXW
2      CUSOUC36C3VO4K1
3      CUSWPCL0315EVMS
4      CUS3BO17ECYHN3K
...                ...
14994  CUS7715GVE98ABH
14995  CUS64O2OI2T2UON
14996  CUSO891J0ISAZ1E
14997  CUSWMIZA92T97IP
14998  CUSLD794LDMNXOU

[14999 rows x 1 columns]

In [68]:
query = """
SELECT
a.account_type,
AVG(l.loan_amount) AS Avg_Loan
FROM accounts a
JOIN loans l
ON a.customer_id=l.customer_id
GROUP BY a.account_type;
"""

con.execute(query).df()

  account_type       Avg_Loan
0      Savings  150048.764948
1     Business  150760.288407
2     Checking  150873.949510

In [69]:
query = """
SELECT
account_type,
SUM(balance_usd)*100/
(SUM(SUM(balance_usd)) OVER()) AS Deposit_Percentage
FROM accounts
GROUP BY account_type;
"""

con.execute(query).df()

  account_type  Deposit_Percentage
0      Savings           33.302830
1     Checking           33.442063
2     Business           33.255107

In [70]:
query = """
SELECT
city,
MAX(credit_score) AS Highest_Credit
FROM customers
GROUP BY city;
"""

con.execute(query).df()

                    city  Highest_Credit
0           Martinezside             666
1           Gallowayfurt             670
2             Morrisview             573
3              Lake Anna             839
4         New Javierbury             694
...                  ...             ...
25164  North Danielshire             446
25165    North Jacobbury             515
25166     Lake Tylerview             687
25167   West Bradleyside             419
25168  West Herberthaven             816

[25169 rows x 2 columns]

In [71]:
query = """
SELECT
city,
MIN(credit_score) AS Lowest_Credit
FROM customers
GROUP BY city;
"""

con.execute(query).df()

                    city  Lowest_Credit
0           Martinezside            461
1           Gallowayfurt            670
2             Morrisview            573
3              Lake Anna            319
4         New Javierbury            694
...                  ...            ...
25164  North Danielshire            446
25165    North Jacobbury            515
25166     Lake Tylerview            687
25167   West Bradleyside            419
25168  West Herberthaven            816

[25169 rows x 2 columns]

In [72]:
query = """
SELECT
CASE
WHEN credit_score>=750 THEN 'Excellent'
WHEN credit_score>=650 THEN 'Good'
WHEN credit_score>=550 THEN 'Average'
ELSE 'Poor'
END AS Category,
COUNT(*) AS Customers
FROM customers
GROUP BY Category;
"""

con.execute(query).df()

    Category  Customers
0       Poor      22637
1    Average       9253
2       Good       9071
3  Excellent       9039

In [73]:
query = """
SELECT
city,
COUNT(*) AS Customers
FROM customers
GROUP BY city
ORDER BY Customers DESC
LIMIT 10;
"""

con.execute(query).df()

            city  Customers
0  South Michael         51
1     Smithmouth         50
2    New Michael         50
3   West Michael         46
4   East Michael         44
5   Port Michael         40
6  North Michael         38
7      New James         38
8     Port David         38
9    South David         36

In [74]:
query = """
SELECT
c.city,
SUM(a.balance_usd) AS Deposit
FROM customers c
JOIN accounts a
ON c.customer_id=a.customer_id
GROUP BY c.city
ORDER BY Deposit DESC
LIMIT 10;
"""

con.execute(query).df()

            city     Deposit
0     Smithmouth  8517346.17
1    South James  7930640.45
2   West Michael  7644937.54
3  South Michael  7298808.93
4  North Michael  7297025.87
5    North David  6802515.36
6    New Michael  6588158.85
7      New David  6563222.42
8   Port Michael  5998825.53
9      New James  5651742.96

In [75]:
query = """
SELECT
SUM(l.loan_amount)/SUM(a.balance_usd) AS Loan_Deposit_Ratio
FROM loans l
JOIN accounts a
ON l.customer_id=a.customer_id;
"""

con.execute(query).df()

   Loan_Deposit_Ratio
0            1.505461

In [76]:
query = """
WITH Deposit AS
(
SELECT
customer_id,
SUM(balance_usd) AS Total_Deposit
FROM accounts
GROUP BY customer_id
)

SELECT *
FROM Deposit
WHERE Total_Deposit > 50000;
"""

con.execute(query).df()

           customer_id  Total_Deposit
0      CUSAEOACKBH8CK6      389215.84
1      CUSKI0ABUBGCLFD       57886.71
2      CUSNUWQT2EXWNSC      259740.50
3      CUSDMISW804XPRO      806282.32
4      CUSSI6L5SODYNTG      548917.89
...                ...            ...
34350  CUSTDESY3U0SL3E      141105.21
34351  CUSTN75FSRMW2Q7      125666.08
34352  CUSHZBT69161GTD      154144.89
34353  CUS8V82IR3C5XZX      148488.33
34354  CUS4WVVOPXXEGSB      119505.81

[34355 rows x 2 columns]

In [77]:
query = """
SELECT
COUNT(DISTINCT c.customer_id) AS Customers,
COUNT(DISTINCT a.account_id) AS Accounts,
COUNT(DISTINCT l.loan_id) AS Loans,
SUM(a.balance_usd) AS Total_Deposit,
SUM(l.loan_amount) AS Total_Loan,
AVG(c.credit_score) AS Avg_Credit_Score
FROM customers c
LEFT JOIN accounts a
ON c.customer_id=a.customer_id
LEFT JOIN loans l
ON c.customer_id=l.customer_id;
"""

con.execute(query).df()

   Customers  Accounts  Loans  Total_Deposit    Total_Loan  Avg_Credit_Score
0      50000     75000  30000   8.613604e+09  7.755020e+09        574.247476

In [78]:
query = """
SELECT customer_id,
COUNT(account_id) AS Total_Accounts
FROM accounts
GROUP BY customer_id
HAVING COUNT(account_id) > 1;
"""

con.execute(query).df()

           customer_id  Total_Accounts
0      CUSAEOACKBH8CK6               3
1      CUSNUWQT2EXWNSC               3
2      CUSDMISW804XPRO               6
3      CUSSI6L5SODYNTG               5
4      CUSBQNS6ND3E3D8               3
...                ...             ...
22216  CUS78EEZI3M9TR5               2
22217  CUSZY6EFO7M2QGN               2
22218  CUSY7UPGM40V36E               2
22219  CUS2LHGCSOTDHHL               2
22220  CUSVU34V20T6MG9               2

[22221 rows x 2 columns]

In [79]:
query = """
SELECT customer_id,
COUNT(loan_id) AS Total_Loans
FROM loans
GROUP BY customer_id
HAVING COUNT(loan_id) > 1;
"""

con.execute(query).df()

          customer_id  Total_Loans
0     CUSK3SW6KH12S96            2
1     CUS8WNWNJT6GKU0            2
2     CUSYFUY9D3ZAL7O            2
3     CUSJSEP0SJGKQQA            2
4     CUS1SZGLXDDEWJK            2
...               ...          ...
6033  CUSBS7IN20Q3HEC            2
6034  CUSO4BEP88JGT9O            2
6035  CUSFKVOMX712GSE            2
6036  CUSVOAAP4ASLTC3            2
6037  CUSFJJ1VKCF9SBA            2

[6038 rows x 2 columns]

In [81]:
query = """
SELECT a.customer_id,
COUNT(c.card_id) AS Total_Cards
FROM cards c
JOIN accounts a
ON c.account_id = a.account_id
GROUP BY a.customer_id
HAVING COUNT(c.card_id) > 1;
"""

con.execute(query).df()

           customer_id  Total_Cards
0      CUSQ6SVR0IIWV25            7
1      CUSBL0EHSMGYRFH            2
2      CUSKN5Z1LYHBW53            6
3      CUSJE6E8T82LZH3            4
4      CUSVCINK4ES71I3            4
...                ...          ...
24813  CUSM3TZK3NY9V20            2
24814  CUSK4OTBGDPUH4G            2
24815  CUSTF29U37SUR2K            2
24816  CUSY5GGIKPH8M2F            2
24817  CUSN26MDUS5N0I4            2

[24818 rows x 2 columns]

In [82]:
query = """
SELECT
COUNT(account_id)*1.0/COUNT(DISTINCT customer_id) AS Avg_Accounts_Per_Customer
FROM accounts;
"""

con.execute(query).df()

   Avg_Accounts_Per_Customer
0                   1.931098

In [84]:
query = """
SELECT
COUNT(c.card_id)*1.0/COUNT(DISTINCT a.customer_id) AS Avg_Cards_Per_Customer
FROM cards c
JOIN accounts a ON c.account_id = a.account_id;
"""

con.execute(query).df()

   Avg_Cards_Per_Customer
0                2.984718

In [85]:
query = """
SELECT
COUNT(loan_id)*1.0/COUNT(DISTINCT customer_id) AS Avg_Loans_Per_Customer
FROM loans;
"""

con.execute(query).df()

   Avg_Loans_Per_Customer
0                1.328256

In [86]:
query = """
SELECT customer_id
FROM customers
WHERE customer_id NOT IN
(
SELECT customer_id
FROM loans
);
"""

con.execute(query).df()

           customer_id
0      CUSHXTHV3A3ZMF8
1      CUSGCX1945NQ4FM
2      CUSVG0FN9XUY41I
3      CUSPVN9ER14FFYV
4      CUSOYN6QICATVAZ
...                ...
27409  CUSDJ8GIMJBQ1OQ
27410  CUS287HK3W659NS
27411  CUS3393NRRUTTA9
27412  CUSDT2QC0P1XO65
27413  CUS9U01H8I3F6EA

[27414 rows x 1 columns]

In [95]:
query = """
SELECT c.customer_id
FROM customers c
WHERE NOT EXISTS (
    SELECT 1
    FROM accounts a
    JOIN cards ca
      ON a.account_id = ca.account_id
    WHERE a.customer_id = c.customer_id
);
"""

con.execute(query).df()

           customer_id
0      CUST2D5EM2VAJEP
1      CUS4PDZP6LFEWVZ
2      CUS1IEIXWC4RTWU
3      CUS1K9YE9O2M71H
4      CUS8HL88KZRUIN3
...                ...
16491  CUSMX4G9MJ5WO5K
16492  CUSTT1J6L8DAURZ
16493  CUSXPY7700MOKJL
16494  CUSEC2URAP1OKPO
16495  CUS51WXR4RAG9PM

[16496 rows x 1 columns]

In [96]:
query = """
SELECT customer_id
FROM customers
WHERE customer_id NOT IN
(
SELECT customer_id
FROM accounts
);
"""

con.execute(query).df()

           customer_id
0      CUSHXTHV3A3ZMF8
1      CUS877VREN93IIU
2      CUSTFGQ5C34DXTA
3      CUSIOYKL1CQ99CH
4      CUS7EEDTJVZHWJR
...                ...
11157  CUSGKURPSL7LNIV
11158  CUSV942FEOLVOZD
11159  CUS287HK3W659NS
11160  CUSDT2QC0P1XO65
11161  CUS9U01H8I3F6EA

[11162 rows x 1 columns]

In [98]:
query = """
SELECT DISTINCT c.customer_id
FROM customers c
JOIN accounts a ON c.customer_id=a.customer_id
JOIN loans l ON c.customer_id=l.customer_id
JOIN cards ca ON a.account_id=ca.account_id;
"""

con.execute(query).df()

           customer_id
0      CUSWXG0ESCUG77M
1      CUS9YL8T9J6JVFB
2      CUSA9P9URVI8PJ6
3      CUSIYHG2C1W6RSP
4      CUSWQQRDU9YFR1G
...                ...
14994  CUSKMRL48297GBK
14995  CUSTLRSOQS8OM7N
14996  CUS8XC0900I4U6J
14997  CUSDDX34NIFI4DA
14998  CUSFWA5JF7OASE3

[14999 rows x 1 columns]

In [99]:
query = """
SELECT customer_id,
SUM(loan_amount) AS Total_Loan
FROM loans
GROUP BY customer_id
ORDER BY Total_Loan DESC
LIMIT 10;
"""

con.execute(query).df()

       customer_id  Total_Loan
0  CUSYBG0PBC27EAS  1123514.67
1  CUSA2YA9PLX5W5K  1010518.24
2  CUST5290S2MIRYR   978201.47
3  CUSPORUG0V6A71N   972512.87
4  CUSMX92M9VM90EI   958563.60
5  CUSIGN7DG56ER0X   953273.77
6  CUSX9CT17KVHTKL   926457.34
7  CUSZQP07G7XR8AD   913251.84
8  CUSH5GOH2M9BMDI   902852.46
9  CUS6TIDFXYBMJW1   899039.30

In [100]:
query = """
SELECT customer_id,
credit_score
FROM customers
ORDER BY credit_score DESC
LIMIT 10;
"""

con.execute(query).df()

       customer_id  credit_score
0  CUS960BMTXV4L9L           850
1  CUSBPOYIQ97DH4I           850
2  CUSKDOFFWS890YM           850
3  CUSS8G8TACY15PD           850
4  CUSHCK1DIV8U36K           850
5  CUS49K5YJCOFNUM           850
6  CUSDKXILEXXYE4Q           850
7  CUSD5EUSC74C5AI           850
8  CUSF9TXMJQP6I0T           850
9  CUSV1T4DEKOX8UQ           850

In [101]:
query = """
SELECT
c.city,
AVG(l.loan_amount) AS Avg_Loan
FROM customers c
JOIN loans l
ON c.customer_id=l.customer_id
GROUP BY c.city;
"""

con.execute(query).df()

                     city       Avg_Loan
0      North Williamville  242746.270000
1                 Amybury  167195.038000
2           West Michelle  161543.222222
3              West Laura  169472.621538
4               Davidstad  131934.808889
...                   ...            ...
14442           Reginaton  175497.800000
14443     North Davidview  159524.243333
14444          West Steve  132286.310000
14445     East Donaldberg  215435.670000
14446           Bowmanton  103115.310000

[14447 rows x 2 columns]

In [102]:
query = """
SELECT
c.city,
SUM(a.balance_usd) AS Total_Balance
FROM customers c
JOIN accounts a
ON c.customer_id=a.customer_id
GROUP BY c.city;
"""

con.execute(query).df()

                     city  Total_Balance
0             Vanessaview      508578.37
1           Lake Johntown      711174.85
2             Laurieburgh      806282.32
3               Jamesland     2173684.44
4               Ricehaven      483594.18
...                   ...            ...
21214       Saundersburgh      123027.72
21215  West Gabriellestad      165694.10
21216     South Codyville       45795.84
21217   South Patricktown       47595.95
21218         New Bridget      141105.21

[21219 rows x 2 columns]

In [103]:
query = """
SELECT
c.city,
SUM(l.loan_amount)*100.0/
SUM(SUM(l.loan_amount)) OVER() AS Loan_Percentage
FROM customers c
JOIN loans l
ON c.customer_id=l.customer_id
GROUP BY c.city;
"""

con.execute(query).df()

                   city  Loan_Percentage
0          Gallowayfurt         0.002775
1        South Jennifer         0.053647
2          Vanessahaven         0.004717
3              Chadport         0.009178
4      Port Tammieshire         0.004498
...                 ...              ...
14442        North Emma         0.003601
14443  North Andreaport         0.006162
14444       Comptonstad         0.004445
14445      Jerrychester         0.000863
14446       North Craig         0.001097

[14447 rows x 2 columns]

In [104]:
query = """
SELECT
customer_id,
balance_usd,
CASE
WHEN balance_usd < 5000 THEN 'Low'
WHEN balance_usd BETWEEN 5000 AND 20000 THEN 'Medium'
ELSE 'High'
END AS Deposit_Class
FROM accounts;
"""

con.execute(query).df()

           customer_id  balance_usd Deposit_Class
0      CUSAEOACKBH8CK6    182700.46          High
1      CUSKI0ABUBGCLFD     57886.71          High
2      CUSWXG0ESCUG77M     68774.44          High
3      CUSUTT52LK3TW0J     67015.68          High
4      CUSNUWQT2EXWNSC     67265.67          High
...                ...          ...           ...
74995  CUSML6DVZNVOTES     64095.88          High
74996  CUSIHEDKAB0C7FW     13904.42        Medium
74997  CUSFEW5CWHU9HZK     19009.31        Medium
74998  CUSO0NX8NPL40L2     87440.52          High
74999  CUST84K7Y8VI7GY     63892.97          High

[75000 rows x 3 columns]

In [105]:
query = """
SELECT c.city,
MAX(l.loan_amount) AS Highest_Loan
FROM customers c
JOIN loans l
ON c.customer_id=l.customer_id
GROUP BY c.city;
"""

con.execute(query).df()

                   city  Highest_Loan
0          Gallowayfurt     122486.98
1        South Jennifer     296046.12
2          Vanessahaven     204372.03
3              Chadport     217845.85
4      Port Tammieshire     124275.66
...                 ...           ...
14442        North Emma     162143.67
14443  North Andreaport     277471.37
14444       Comptonstad     200157.84
14445      Jerrychester      38880.42
14446       North Craig      49407.19

[14447 rows x 2 columns]

In [106]:
query = """
SELECT c.city,
MAX(a.balance_usd) AS Highest_Deposit
FROM customers c
JOIN accounts a
ON c.customer_id=a.customer_id
GROUP BY c.city;
"""

con.execute(query).df()

                    city  Highest_Deposit
0            Vanessaview        177035.71
1          Lake Johntown        196035.77
2            Laurieburgh        198611.58
3              Jamesland        193748.23
4              Ricehaven        164330.33
...                  ...              ...
21214   Lake Andrewshire        178892.63
21215  West Brentchester        179843.69
21216   New Matthewville         67071.64
21217    Port Rachelview         12726.76
21218      Port Lawrence        154144.89

[21219 rows x 2 columns]

In [107]:
query = """
SELECT *
FROM loans
WHERE loan_amount >
(
SELECT AVG(loan_amount)
FROM loans
);
"""

con.execute(query).df()

,loan_id,customer_id,loan_amount,interest_rate,start_date
0,LONHREM3GBFRZCN,CUSK3SW6KH12S96,176269.07,3.84,2022-12-12
1,LONRVF09SWTR92A,CUS7D2AZQQGCDHI,193167.37,10.97,2024-06-01
2,LONHDREEA5JR90K,CUS7BPAAKLYYY42,196049.13,8.10,2024-08-02
3,LONR1E6D7SHGHKT,CUSFY357STKLGR8,174356.26,5.26,2020-07-20
4,LON1ISOKTAMO1RT,CUSXOL4RMHAJ3F0,178071.99,2.75,2025-08-16
...,...,...,...,...,...
15033,LONHKEG9UINT2MP,CUS0FQ3OIG5WS87,254622.96,4.08,2025-05-28
15034,LONB1DZ8TFK64IU,CUSRGGI1641R4FQ,187417.92,12.04,2023-02-15
15035,LONFV13QJYAHX3F,CUS68EE2OONL01A,275507.35,12.04,2019-09-18
15036,LONO4EQ9BRMKRIS,CUSM7RPWD1JR091,263122.44,7.74,2019-12-14
15037,LONLW9WCOJMI69J,CUSD29F8PX71M8E,289248.96,4.34,2021-07-08

In [109]:
query = """
SELECT
COUNT(DISTINCT c.customer_id) AS Total_Customers,
COUNT(DISTINCT a.account_id) AS Total_Accounts,
COUNT(DISTINCT l.loan_id) AS Total_Loans,
COUNT(DISTINCT ca.card_id) AS Total_Cards,
SUM(a.balance_usd) AS Total_Deposits,
SUM(l.loan_amount) AS Total_Loan_Amount,
AVG(c.credit_score) AS Avg_Credit_Score,
AVG(l.interest_rate) AS Avg_Interest_Rate
FROM customers c
LEFT JOIN accounts a ON c.customer_id=a.customer_id
LEFT JOIN loans l ON c.customer_id=l.customer_id
LEFT JOIN cards ca ON a.account_id=ca.account_id;
"""

con.execute(query).df()

,Total_Customers,Total_Accounts,Total_Loans,Total_Cards,Total_Deposits,Total_Loan_Amount,Avg_Credit_Score,Avg_Interest_Rate
0,50000,75000,30000,100000,1.375494e+10,1.180584e+10,574.27484,8.485911

In [110]:
query = """
SELECT
customer_id,
balance_usd,
LAG(balance_usd) OVER(ORDER BY balance_usd) AS Previous_Deposit
FROM accounts;
"""

con.execute(query).df()

           customer_id  balance_usd  Previous_Deposit
0      CUS27D326TP8SFA        13.20               NaN
1      CUSHQQESGMMT2GL        13.21             13.20
2      CUSM21QSNKM1LDM        26.44             13.21
3      CUSXZ5IST4T86UZ        27.59             26.44
4      CUSWJRLKU8F1OP9        28.55             27.59
...                ...          ...               ...
74995  CUSXKDR73U5XXC8    199965.37         199963.49
74996  CUSFSEINJWX8QJ5    199968.62         199965.37
74997  CUSTCFNYEBCRW2Y    199969.50         199968.62
74998  CUS05F95VDL5G26    199989.26         199969.50
74999  CUSEXB4Z7J8HWE2    199994.58         199989.26

[75000 rows x 3 columns]

In [111]:
query = """
SELECT
customer_id,
balance_usd,
LEAD(balance_usd) OVER(ORDER BY balance_usd) AS Next_Deposit
FROM accounts;
"""

con.execute(query).df()

           customer_id  balance_usd  Next_Deposit
0      CUS27D326TP8SFA        13.20         13.21
1      CUSHQQESGMMT2GL        13.21         26.44
2      CUSM21QSNKM1LDM        26.44         27.59
3      CUSXZ5IST4T86UZ        27.59         28.55
4      CUSWJRLKU8F1OP9        28.55         35.49
...                ...          ...           ...
74995  CUSXKDR73U5XXC8    199965.37     199968.62
74996  CUSFSEINJWX8QJ5    199968.62     199969.50
74997  CUSTCFNYEBCRW2Y    199969.50     199989.26
74998  CUS05F95VDL5G26    199989.26     199994.58
74999  CUSEXB4Z7J8HWE2    199994.58           NaN

[75000 rows x 3 columns]

In [112]:
query = """
SELECT
customer_id,
balance_usd,
NTILE(4) OVER(ORDER BY balance_usd DESC) AS Quartile
FROM accounts;
"""

con.execute(query).df()

           customer_id  balance_usd  Quartile
0      CUSEXB4Z7J8HWE2    199994.58         1
1      CUS05F95VDL5G26    199989.26         1
2      CUSTCFNYEBCRW2Y    199969.50         1
3      CUSFSEINJWX8QJ5    199968.62         1
4      CUSXKDR73U5XXC8    199965.37         1
...                ...          ...       ...
74995  CUSWJRLKU8F1OP9        28.55         4
74996  CUSXZ5IST4T86UZ        27.59         4
74997  CUSM21QSNKM1LDM        26.44         4
74998  CUSHQQESGMMT2GL        13.21         4
74999  CUS27D326TP8SFA        13.20         4

[75000 rows x 3 columns]

In [113]:
query = """
SELECT
customer_id,
balance_usd,
FIRST_VALUE(balance_usd)
OVER(ORDER BY balance_usd DESC) AS Highest_Deposit
FROM accounts;
"""

con.execute(query).df()

           customer_id  balance_usd  Highest_Deposit
0      CUSEXB4Z7J8HWE2    199994.58        199994.58
1      CUS05F95VDL5G26    199989.26        199994.58
2      CUSTCFNYEBCRW2Y    199969.50        199994.58
3      CUSFSEINJWX8QJ5    199968.62        199994.58
4      CUSXKDR73U5XXC8    199965.37        199994.58
...                ...          ...              ...
74995  CUSWJRLKU8F1OP9        28.55        199994.58
74996  CUSXZ5IST4T86UZ        27.59        199994.58
74997  CUSM21QSNKM1LDM        26.44        199994.58
74998  CUSHQQESGMMT2GL        13.21        199994.58
74999  CUS27D326TP8SFA        13.20        199994.58

[75000 rows x 3 columns]

In [114]:
query = """
SELECT
customer_id,
balance_usd,
LAST_VALUE(balance_usd)
OVER(
ORDER BY balance_usd
ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
) AS Lowest_Deposit
FROM accounts;
"""

con.execute(query).df()

           customer_id  balance_usd  Lowest_Deposit
0      CUS27D326TP8SFA        13.20       199994.58
1      CUSHQQESGMMT2GL        13.21       199994.58
2      CUSM21QSNKM1LDM        26.44       199994.58
3      CUSXZ5IST4T86UZ        27.59       199994.58
4      CUSWJRLKU8F1OP9        28.55       199994.58
...                ...          ...             ...
74995  CUSXKDR73U5XXC8    199965.37       199994.58
74996  CUSFSEINJWX8QJ5    199968.62       199994.58
74997  CUSTCFNYEBCRW2Y    199969.50       199994.58
74998  CUS05F95VDL5G26    199989.26       199994.58
74999  CUSEXB4Z7J8HWE2    199994.58       199994.58

[75000 rows x 3 columns]

In [115]:
query = """
SELECT customer_id
FROM accounts

UNION

SELECT customer_id
FROM loans;
"""

con.execute(query).df()

           customer_id
0      CUSK3SW6KH12S96
1      CUS7D2AZQQGCDHI
2      CUSJ7KYVHT6ZWCH
3      CUSXOL4RMHAJ3F0
4      CUSIUFWOFRYTP4D
...                ...
43997  CUSOQVNPZO3SQUF
43998  CUSTDESY3U0SL3E
43999  CUSTN75FSRMW2Q7
44000  CUSHZBT69161GTD
44001  CUS8V82IR3C5XZX

[44002 rows x 1 columns]

In [116]:
query = """
SELECT customer_id
FROM accounts

UNION ALL

SELECT customer_id
FROM loans;
"""

con.execute(query).df()

            customer_id
0       CUSAEOACKBH8CK6
1       CUSKI0ABUBGCLFD
2       CUSWXG0ESCUG77M
3       CUSUTT52LK3TW0J
4       CUSNUWQT2EXWNSC
...                 ...
104995  CUSIHFOD47MD1TH
104996  CUSMSQJ1410AY5T
104997  CUSN7BLFRKNNIMC
104998  CUS9J49Q207YU5Q
104999  CUSJJZ858O0J3T8

[105000 rows x 1 columns]

In [117]:
query = """
SELECT customer_id
FROM accounts

INTERSECT

SELECT customer_id
FROM loans;
"""

con.execute(query).df()

           customer_id
0      CUSKI0ABUBGCLFD
1      CUSDMISW804XPRO
2      CUSEYPA6FVBD9S2
3      CUSUI060YGC5RCB
4      CUSK7K0H4F3JWB2
...                ...
17417  CUSIOODFTVNGJPW
17418  CUSTYAQ35QAN5GM
17419  CUS4BR0ODN8X2D8
17420  CUSTTXZXKAHOT55
17421  CUS4WVVOPXXEGSB

[17422 rows x 1 columns]

In [118]:
query = """
SELECT customer_id
FROM accounts

EXCEPT

SELECT customer_id
FROM loans;
"""

con.execute(query).df()

           customer_id
0      CUSAEOACKBH8CK6
1      CUSNUWQT2EXWNSC
2      CUSSI6L5SODYNTG
3      CUSBQNS6ND3E3D8
4      CUSXPAWQPOE9FWC
...                ...
21411  CUSOQVNPZO3SQUF
21412  CUSTDESY3U0SL3E
21413  CUSTN75FSRMW2Q7
21414  CUSHZBT69161GTD
21415  CUS8V82IR3C5XZX

[21416 rows x 1 columns]

In [119]:
query = """
SELECT
city,
COUNT(*) AS Customers
FROM customers
GROUP BY city
HAVING COUNT(*) > 100;
"""

con.execute(query).df()

Empty DataFrame
Columns: [city, Customers]
Index: []

In [120]:
query = """
SELECT city,
COUNT(*) AS Total_Customers
FROM customers
GROUP BY city
HAVING COUNT(*) >
(
SELECT AVG(Customer_Count)
FROM
(
SELECT COUNT(*) AS Customer_Count
FROM customers
GROUP BY city
) t
);
"""

con.execute(query).df()

                     city  Total_Customers
0      North Williamville                3
1                 Amybury                6
2           West Michelle               13
3              West Laura               17
4               Davidstad               16
...                   ...              ...
8912          New Cameron                2
8913           Louishaven                2
8914  South Jonathanhaven                2
8915             Holtland                2
8916         South Rhonda                2

[8917 rows x 2 columns]

In [121]:
query = """
WITH Deposits AS
(
SELECT
customer_id,
SUM(balance_usd) AS Total_Deposit
FROM accounts
GROUP BY customer_id
)

SELECT *
FROM Deposits
ORDER BY Total_Deposit DESC
LIMIT 10;
"""

con.execute(query).df()

       customer_id  Total_Deposit
0  CUSEPV1YW0Y2JL9     1020344.41
1  CUSN2LWQV1UR1PY      998074.92
2  CUS3JY2UIFZ7123      935146.22
3  CUSM3X4B2DTTNOO      932783.59
4  CUSHMODKKCZTNRF      928661.73
5  CUSVFI1KMDWBWNP      888434.52
6  CUSIJ61KQCG1IV8      885857.36
7  CUSXVL4YRQRDZHJ      859286.03
8  CUSHMDV47IQRPIC      851916.54
9  CUSDCD4K37ULEHP      840288.34

In [122]:
query = """
SELECT
customer_id,
credit_score,
PERCENT_RANK()
OVER(ORDER BY credit_score) AS Percentile
FROM customers;
"""

con.execute(query).df()

           customer_id  credit_score  Percentile
0      CUSRV2Y7CDABBAJ           300     0.00000
1      CUSPRO6DUTJTO91           300     0.00000
2      CUSP7WZITMFEYAD           300     0.00000
3      CUSUYQO89LG7V6T           300     0.00000
4      CUSHVYRONADCVMS           300     0.00000
...                ...           ...         ...
49995  CUS4D8MRK3B4OF4           850     0.99796
49996  CUS2HDCS61HW5KB           850     0.99796
49997  CUSPRSX0NI18V69           850     0.99796
49998  CUS9ITA3UK5W2GY           850     0.99796
49999  CUS0T9T40QTKUL9           850     0.99796

[50000 rows x 3 columns]

In [123]:
query = """
SELECT
customer_id,
loan_amount,
SUM(loan_amount)
OVER(ORDER BY loan_amount) AS Running_Loan
FROM loans;
"""

con.execute(query).df()

           customer_id  loan_amount  Running_Loan
0      CUSAJBC9Z2F0C63      1010.16  1.010160e+03
1      CUS137BJGHJ9JWH      1015.54  2.025700e+03
2      CUSQ7ACXAH9KCO3      1020.04  3.045740e+03
3      CUSRJZBZMT6Y6TL      1033.24  4.078980e+03
4      CUSRF3NAPLGW1XL      1043.08  5.122060e+03
...                ...          ...           ...
29995  CUSSF97K7GTGZ33    299933.30  4.501471e+09
29996  CUSDMS8KRN7JG60    299951.14  4.501771e+09
29997  CUSSV1SPPFFGX3Y    299959.70  4.502071e+09
29998  CUSPYS71SMSGB52    299967.79  4.502371e+09
29999  CUS9R8QO64GS540    299975.47  4.502670e+09

[30000 rows x 3 columns]

In [124]:
query = """
SELECT
loan_id,
loan_amount,
loan_amount -
AVG(loan_amount) OVER() AS Difference_From_Average
FROM loans;
"""

con.execute(query).df()

               loan_id  loan_amount  Difference_From_Average
0      LONVIJLFE0FQERD      7939.97           -142149.046603
1      LONHREM3GBFRZCN    176269.07             26180.053397
2      LONRVF09SWTR92A    193167.37             43078.353397
3      LONVIO8NY2TPJ97     15623.54           -134465.476603
4      LON8MO4Z8F2MY71     50695.04            -99393.976603
...                ...          ...                      ...
29995  LONL9HZM88R8JIU     40342.96           -109746.056603
29996  LON1PWZOB6KC7UR     70458.49            -79630.526603
29997  LON1IFMTOA1JH47     65763.57            -84325.446603
29998  LONKW49Q0F6TJ0P     96598.60            -53490.416603
29999  LON253K6CDPON7O      2262.57           -147826.446603

[30000 rows x 3 columns]

In [125]:
query = """
SELECT
account_id,
balance_usd,
balance_usd -
AVG(balance_usd) OVER() AS Difference_From_Average
FROM accounts;
"""

con.execute(query).df()

            account_id  balance_usd  Difference_From_Average
0      ACCOD48PUCAEHKH    182700.46             82518.738119
1      ACCU2DMTSOYD5R6     57886.71            -42295.011881
2      ACCXFI6TF26FL9B     68774.44            -31407.281881
3      ACCJ6SUS4ZI6BRT     67015.68            -33166.041881
4      ACCNP7JE3AQW8TG     67265.67            -32916.051881
...                ...          ...                      ...
74995  ACCJW0MLLOWSYE4     64095.88            -36085.841881
74996  ACCWRMKX68RGFCM     13904.42            -86277.301881
74997  ACCXF6ZRSQ2VDVC     19009.31            -81172.411881
74998  ACC2LO5YE5GZBCO     87440.52            -12741.201881
74999  ACCRJMJ63PIKISI     63892.97            -36288.751881

[75000 rows x 3 columns]

In [126]:
query = """
SELECT *
FROM
(
SELECT
c.city,
a.customer_id,
SUM(a.balance_usd) AS Deposit,
ROW_NUMBER() OVER
(
PARTITION BY c.city
ORDER BY SUM(a.balance_usd) DESC
) AS rn
FROM customers c
JOIN accounts a
ON c.customer_id=a.customer_id
GROUP BY c.city,a.customer_id
) x
WHERE rn=1;
"""

con.execute(query).df()

               city      customer_id    Deposit  rn
0       Abigailstad  CUS08YIOBZVW71O   83401.22   1
1        Adamsburgh  CUSPJ1AKW007NBP  133582.39   1
2        Adamsshire  CUSVTAKAHAB1Q2H  203809.67   1
3          Adamstad  CUSOD9Y7UOQYZKW  140236.48   1
4        Adkinsfurt  CUSVRX3UEZ95QC1  694974.77   1
...             ...              ...        ...  ..
21214     Youngberg  CUSBB5YFTXDXNAD  313032.98   1
21215  Youngchester  CUSKQCZEQUTL1KU  257123.38   1
21216     Youngfort  CUSECXWYYBB1WCG  197720.83   1
21217        Yuside  CUSBUBQMLX9WDBG  277882.58   1
21218     Zhangbury  CUSWSJY3FQ81H8L   48025.31   1

[21219 rows x 4 columns]

In [127]:
query = """
SELECT *
FROM
(
SELECT
c.city,
l.customer_id,
SUM(l.loan_amount) AS Loan,
ROW_NUMBER() OVER
(
PARTITION BY c.city
ORDER BY SUM(l.loan_amount) DESC
) AS rn
FROM customers c
JOIN loans l
ON c.customer_id=l.customer_id
GROUP BY c.city,l.customer_id
) x
WHERE rn=1;
"""

con.execute(query).df()

                   city      customer_id       Loan  rn
0         New Carlaview  CUS56TIZANKUMY7  430602.90   1
1      New Charlesmouth  CUS4JMHVK8SSRI5  441708.29   1
2       New Charlestown  CUST4C46P9NBAV4  434941.45   1
3         New Dannystad  CUSFWKJWWW7IB2M   72468.92   1
4        New Davidmouth  CUS0JDYKYK020O5  227611.33   1
...                 ...              ...        ...  ..
14442       Wrightshire  CUS8MQ1VVAG71MG  321931.12   1
14443        Wrightstad  CUSN04ZVVEY60AH  271390.80   1
14444        Youngshire  CUS8VEIA6ZT3296  432426.28   1
14445        Youngville  CUS6265N2NP3ARG  571115.39   1
14446      Zacharyshire  CUSDS8IUCJ4I0AJ  206174.91   1

[14447 rows x 4 columns]

In [130]:
query = """
SELECT
c.customer_id,
COUNT(DISTINCT a.account_id) AS Accounts,
COUNT(DISTINCT l.loan_id) AS Loans,
COUNT(DISTINCT ca.card_id) AS Cards,
SUM(a.balance_usd) AS Deposits,
SUM(l.loan_amount) AS Loans_Amount
FROM customers c
LEFT JOIN accounts a
ON c.customer_id=a.customer_id
LEFT JOIN loans l
ON c.customer_id=l.customer_id
LEFT JOIN cards ca
ON a.account_id=ca.account_id
GROUP BY c.customer_id;
"""

con.execute(query).df()

           customer_id  Accounts  Loans  Cards    Deposits  Loans_Amount
0      CUS1PVOPNQ5NOIN         4      1     12  1406135.72     191178.72
1      CUSFLE69M3I1RAJ         1      0      3   141721.50           NaN
2      CUSY56VWIOYTCHK         2      0      6   146674.40           NaN
3      CUSLIU05PJZJRFC         5      0      5   432353.54           NaN
4      CUSC8HPR9CJOJXW         3      2      6  1595827.80    1417494.60
...                ...       ...    ...    ...         ...           ...
49995  CUSN6SVUNWNMTG3         1      1      0   135453.69     195013.78
49996  CUS3DUTO5US8QG7         1      0      0   154249.40           NaN
49997  CUS6PHK5RI7DQ8W         1      1      0     9814.47     250762.20
49998  CUSRD130LR546G2         1      0      0   181528.11           NaN
49999  CUS4E95OOAE1FVY         1      0      0    29579.84           NaN

[50000 rows x 6 columns]

In [131]:
query = """
SELECT
COUNT(DISTINCT c.customer_id) AS Customers,
COUNT(DISTINCT a.account_id) AS Accounts,
COUNT(DISTINCT l.loan_id) AS Loans,
COUNT(DISTINCT ca.card_id) AS Cards,
SUM(a.balance_usd) AS Deposits,
SUM(l.loan_amount) AS Loan_Amount,
AVG(c.credit_score) AS Avg_Credit_Score,
AVG(l.interest_rate) AS Avg_Interest_Rate,
SUM(l.loan_amount)/SUM(a.balance_usd) AS Loan_Deposit_Ratio
FROM customers c
LEFT JOIN accounts a
ON c.customer_id=a.customer_id
LEFT JOIN loans l
ON c.customer_id=l.customer_id
LEFT JOIN cards ca
ON a.account_id=ca.account_id;
"""

con.execute(query).df()

,Customers,Accounts,Loans,Cards,Deposits,Loan_Amount,Avg_Credit_Score,Avg_Interest_Rate,Loan_Deposit_Ratio
0,50000,75000,30000,100000,1.375494e+10,1.180584e+10,574.27484,8.485911,0.858298